PARAMETERS = [
    "Date",
    "Time",
    "DeviceName",
    "MAC",
    "LocalIP",
    "RSSI",
    "FW_MainController",
    "FW_WiFi",
    "SystemMode",
    "Speed_In",
    "Speed_Out",
    "Speed_AntiFreeze",
    "Temp_In",
    "Temp_Out",
    "Temp_Fresh",
    "rel_Humidity_In",
    "rel_Humidity_Out",
    "abs_Humidity_In",
    "abs_Humidity_Out",
    "Efficiency",
    "Humidity_Transport",
    "_SystemOn",
    "_FrostschutzAktiv",
    "_Frozen",
    "_AbtauMode",
    "_VermieterMode",
    "_QuerlueftungAktiv",
    "_MaxMode",
]

CONVERSION_DICT = {
    "Date": datetime.date,
    "Time": "",
    "DeviceName": "",
    "MAC": "",
    "LocalIP": "",
    "RSSI": "",
    "FW_MainController": "",
    "FW_WiFi": "",
    "SystemMode": "",
    "Speed_In": "",
    "Speed_Out": "",
    "Speed_AntiFreeze": "",
    "Temp_In": "",
    "Temp_Out": "",
    "Temp_Fresh": "",
    "rel_Humidity_In": "",
    "rel_Humidity_Out": "",
    "abs_Humidity_In": "",
    "abs_Humidity_Out": "",
    "Efficiency": "",
    "Humidity_Transport": "",
    "_SystemOn": "",
    "_FrostschutzAktiv": "",
    "_Frozen": "",
    "_AbtauMode": "",
    "_VermieterMode": "",
    "_QuerlueftungAktiv": "",
    "_MaxMode": "",
}
